error: Make convert{,_ret}() and convert_if_errno{,ret}() generic
Allow any type for which MinusOneSigned is implemented (which is
basically all built-in signed integer types.)